### ISSUE TITLE
requirements.txt has conflicting marshmallow versions

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/BEAR-Necessities-Market#11]
Following https://github.com/LibreFoodPantry/BEAR-Necessities-Market#application-download--installation .

When I run...

```
$ pip install -r requirements.txt
```

I get...

```
flask-io 1.14.1 has requirement marshmallow==2.9.1, but you'll have marshmallow 2.18.0 which is incompatible.
```

**Comment by hawzie197** [comment]
Flask-io is no longer a "needed" dependency. I will update the requirements.txt accordingly.

Thanks for pointing that out.
