### ISSUE TITLE
Q: Using both unittest and pytest?

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/BEAR-Necessities-Market#27]
https://github.com/LibreFoodPantry/BEAR-Necessities-Market/blob/master/tests/base_case.py uses unittest.

https://github.com/LibreFoodPantry/BEAR-Necessities-Market/blob/master/tests/conftest.py uses pytest.

Is there any reason to use both? Unless there is a good reason, probably should stick to one. Personally I would recommend pytest.

**Comment by hawzie197** [comment]
We originally had unittest set up, butI we are deciding if we should to move towards pytest. Pytest is now more popular, is more compact, simpler and easier to understand when writing tests. Unittest is fine for now though. What are your thoughts?

**Comment by StoneyJackson** [comment]
Love pytest. Dependency injection for fixtures. Simpler syntax. What's not to love?

**Comment by hawzie197** [comment]
Completed.
