### ISSUE TITLE
Tracking .pyc files

### ISSUE THREAD

**Issue by ndion617** [LibreFoodPantry/BEAR-Necessities-Market#29]
Shouldn't be removed and the folders and file extensions added to the git ignore.

**Comment by KevinTran000** [comment]
Anyone knows why there are some cache files committed into this folder and if they were committed in for some special reason?

`./BEAR-Necessities-Market/backend/__pycache__/`

Files in question being: 
- __init__.cpython-36.pyc
- app.cpython-36.pyc
- config.cpython-36.pyc

**Comment by KevinTran000** [comment]
This was completed in PR #42 
The following was added to the git ignore:

- *_\_pycache__
- .pytest_cache

**Comment by StoneyJackson** [comment]
I may have clobbered those changes in PR #42 with those in PR #55.

But [Python.gitignore](https://github.com/LibreFoodPantry/BEAR-Necessities-Market/blob/master/.gitignore.d/Python.gitignore) contains these rules:

```
__pycache__/
.pytest_cache/
```

This first is slightly different from `*__pycache__` which will catch things like `foo__pycache__` and files (not just directories) named `__pycache__`. I don't think we need to catch those. But if we do, we can make the adjustment later.
