### ISSUE TITLE
Design Orders Table

### ISSUE THREAD

**Issue by adhikaribiraj** [LibreFoodPantry/BEAR-Necessities-Market#33]
Present design for class comments on 3/11.

**Comment by alhansrisuk** [comment]
https://github.com/LibreFoodPantry/BEAR-Necessities-Market/projects/3#card-17674705

**Comment by alhansrisuk** [comment]
https://github.com/LibreFoodPantry/BEAR-Necessities-Market/projects/3#card-17675261

**Comment by alhansrisuk** [comment]
https://github.com/LibreFoodPantry/BEAR-Necessities-Market/projects/3#card-17675391

**Comment by alhansrisuk** [comment]
Link to work here: https://docs.google.com/document/d/1HOF0nnZSD13GjqOUWV1NwFT4Fqe-Z-lEIodMl-cvMY0/edit
