### ISSUE TITLE
Set up Pytest

### ISSUE THREAD

**Issue by adhikaribiraj** [LibreFoodPantry/BEAR-Necessities-Market#38]

**Comment by bv349477** [comment]
Pytest was already in requirements.txt

From the pytest website:

**Run multiple tests

pytest will run all files of the form test_*.py or *_test.py in the current directory and its subdirectories. More generally, it follows standard test discovery rules.**

**Comment by hawzie197** [comment]
This has already been completed and can be run with `flask test`
