### ISSUE TITLE
GitHub isn't recognizing license file

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/BEAR-Necessities-Market#39]
When GitHub can recognize the license file, it displays an icon that can tell someone at a glance what license the project is licensed under (assuming the know common licenses).

GitHub isn't recognizing the license file in this project.

I wonder if this is because it is a Markdown file.  So maybe make it plain text? The drawback to this solution would be that it isn't as friendly to read.

**Comment by hawzie197** [comment]
Fixed with #41
