### ISSUE TITLE
Setup travis for automatic testing.

### ISSUE THREAD

**Issue by hawzie197** [LibreFoodPantry/BEAR-Necessities-Market#5]
travis-ci is an excellent platform that integrates seamlessly with github. It will run all unittests for both react and flask whenever someone pushes to a branch, merges a pull request, or tries to deploy to heroku.

Reference: https://travis-ci.org/

**Comment by StoneyJackson** [comment]
Related issues: #24 , #22 , #21

**Comment by hawzie197** [comment]
Fixed in #26
