### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by hawzie197** [LibreFoodPantry/BEAR-Necessities-Market#58]
- Include a much more thorough quick setup guide and getting started guide
- Add a Tech Stack Overview
- Add a code structure to point out what certain directories are used for
- Add a quick link to License
- Add a quick link to discussion page
- Add a thorough documentation file:
    - Include examples like JWT, Routes, DB querying

**Comment by StoneyJackson** [comment]
Is this part of #57?

**Comment by KevinTran000** [comment]
Perhaps also add a section for common issues user may see and the troubleshooting steps for it?

**Comment by StoneyJackson** [comment]
Closing because I think this was all part of #57. For more changes to documentation, please create new issues.
