### ISSUE TITLE
Write a 3 to 4 sentence summary of what the BEAR-Necessities-Market is

### ISSUE THREAD

**Issue by hawzie197** [LibreFoodPantry/BEAR-Necessities-Market#59]
This summary will be placed in the top of the README to inform prospective contributors/users on the purpose of the application.

**Comment by StoneyJackson** [comment]
*clear's throat*

```
This project is a web application that support the needs of WNE's BEAR Necessities Market food pantry.
```

How's that?

**Comment by KevinTran000** [comment]
Maybe mention how later down the road it hopes to add inventory management/tracking capabilities?

> 
> StoneyJackson:
> _clear's throat_
> 
> > This project is a web application that support the needs of WNE's BEAR Necessities Market food pantry. In particular it focuses on placing and filling orders.
> 
> How's that?

**Comment by Strassboom** [comment]
Myself, TimGuy97, and DGSienko are on this.
