### ISSUE TITLE
Where to develop documentation?

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/BEAR-Necessities-Market#68]
Problems with using the wiki for documentation
------------------------------------------------

1. Only contributors can edit the wiki. It is possible to [allow any GitHub user to edit the wiki](https://help.github.com/en/articles/changing-access-permissions-for-wikis). But I don't think we want that either.
2. The wiki does not fork/clone with the code. So if the project ever needs to move, it would be harder with a wiki than if the documentation where in the repository. 
3. Changes to the documentation should follow a review process just like source code. The wiki does not provide this (AFIK).
4. Each release of the project should have its documentation. I don't think GitHub's wiki allows multiple releases to coexist and maintained separately.

Proposal
---------

I recommend that we keep the documentation with the source code in the repository. That way, the documentation is released and maintained with the source and is subject to the same contribution and review process as source.

As an initial structure, I recommend the following:

- `docs/dev/` -  Development environment, contribution process, architecture, ...
- `docs/user/` - Instructions for using the system.
- `docs/admin/` - Instructions for deploying, maintaining, and upgrading a deployment.

As an initial documentation format, I recommend AsciiDoc. It is more powerful than Markdown, more standard/portable than Markdown, is rendered by GitHub as is Markdown, and has a broader mission than Markdown (which specifically targets web pages) and so can be used to generate many other formats. Another alternative to Markdown and AsciiDoc is reStructuredText. After reading the articles below, I have a slight preference for AsciiDoc (although I think a good case could be made for reStructuredText).

- [reStructuredText vs Markdown](http://www.zverovich.net/2016/06/16/rst-vs-markdown.html)
- [AsciiDoc vs Markdown](https://asciidoctor.org/docs/asciidoc-vs-markdown/)
- [Lightweight Markup: Markdown, reStructuredText, MediaWiki, AsciiDoc, Org-mode](http://hyperpolyglot.org/lightweight-markup)

**Comment by KevinTran000** [comment]
Slight amendment proposal:
How about this directory structure?
`/docs/<version>/<bla>/`

i.e.
- `docs/0.1/dev/`
- `docs/0.1/user/`
- `docs/0.1/admin/`
