### ISSUE TITLE
ujson requirement failure

### ISSUE THREAD

**Issue by StefieNguyen** [LibreFoodPantry/BEAR-Necessities-Market#73]
` Running setup.py install for ujson: started
    Running setup.py install for ujson: finished with status 'error'
    Complete output from command c:\users\h103\bear-necessities-market\env\scrip       ts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\h103\\AppD       ata\\Local\\Temp\\pip-install-wy5a3wwu\\ujson\\setup.py';f=getattr(tokenize, 'op       en', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(       code, __file__, 'exec'))" install --record C:\Users\h103\AppData\Local\Temp\pip-       record-ynvetouw\install-record.txt --single-version-externally-managed --compile        --install-headers c:\users\h103\bear-necessities-market\env\include\site\python       3.6\ujson:
    running install
    running build
    running build_ext
    building 'ujson' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual        C++ Build Tools": https://visualstudio.microsoft.com/downloads/
`

**Comment by KevinTran000** [comment]
This appears to be a bug so please supply additional information, for troubleshoot/diagnose.

OS:
32 or 64 bit?:
Memory:

Any other anomalies?: 
Did you ever got it working before, if so what did you do before up to this bug occurring?:

**Comment by KevinTran000** [comment]
Actually, after reading the console print out more in depth, that machine you are running this on is missing `Microsoft Visual C++ 14.0` 
Install that and it should resolve that problem. I believe that comes with Visual Studio install. Make sure you tick off the appropriate box to install it during the installation. (If I remember correctly it was a kinda big install)

**Comment by StoneyJackson** [comment]
@StefieNguyen Solved?

**Comment by KevinTran000** [comment]
@StefieNguyen Was this ever resolved?

**Comment by bv349477** [comment]
Others at https://github.com/benfred/implicit/issues/76 have noted that when following the link in the error message: https://visualstudio.microsoft.com/downloads/ you need to get **Build Tools for Visual Studio 2019** under the **Tools for Visual Studio 2019** tab.

**Comment by bv349477** [comment]
This has a link for both Windows and macOS

**Comment by bv349477** [comment]
The mac terminal command:
xcode-select --install
should get the command line tools to compile C++.
I am not sure myself, would be good if someone else could confirm.
