### ISSUE TITLE
Set up .gitattribute file

### ISSUE THREAD

**Issue by KevinTran000** [LibreFoodPantry/BEAR-Necessities-Market#82]
Set up .gitattribute file to enforce EOLs  (End of Lines, aka Line Endings) in the repo. 

Should be LFs across the board to ensure compatibility with most platforms, also the majority of this program is already written with LF EOLs.

**Comment by KevinTran000** [comment]
I can do this ticket.

**Comment by StoneyJackson** [comment]
Fixed in #98
